services:
  mc_rubrion_server:
    image: container-registry.oracle.com/graalvm/jdk:21
    container_name: mc_rubrion_server
    restart: unless-stopped
    volumes:
      - ./data:/data
    working_dir: /data
    networks:
      - mc_network
    entrypoint: ["/bin/sh", "-c", "chmod +x /data/start.sh && /data/start.sh"]

  haproxy:
    image: haproxy:latest
    container_name: mc_rubrion_haproxy
    restart: unless-stopped
    ports:
      - "25565:25565/tcp"
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    depends_on:
      - mc_rubrion_server
    networks:
      - mc_network

networks:
  mc_network:
    driver: bridge
