services:
  mc_rubrion_server:
    image: container-registry.oracle.com/graalvm/jdk:23
    container_name: mc_rubrion_server
    restart: unless-stopped
    volumes:
      - ./data:/data
    working_dir: /data
    networks:
      - mc_network
    expose:
      - "25565"

  nginx:
    image: nginx:latest
    container_name: mc_rubrion_nginx
    restart: unless-stopped
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
    ports:
      - "25565:25565"
    depends_on:
      - mc_rubrion_server
    networks:
      - mc_network

networks:
  mc_network:
    driver: bridge
